apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: student-frontend-original:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
